### ISSUE TITLE
simplifying a curve?

### ISSUE THREAD

**Issue by mbutterick** [hfutrell/BezierKit#67]
Suppose I delete the marked point on the glyph below. Currently I get the glyph in the second pic, which is not wrong. But it would be more useful to get something closer to the glyph in the third pic (where the remaining Bézier handles have been adjusted to approximate the curve that existed before.).

The question: is there a way to accomplish this in BezierKit? I’m not sure how to characterize this operation. I suppose it would be a sort of curve simplification, where the remaining BCPs are adjusted to produce the curve that’s the closest fit to the one that was there before.

<img width="344" alt="Screen Shot 2020-09-04 at Sep 04  4 43 09 PM" src="https://user-images.githubusercontent.com/1425051/92291517-ebccdf00-eecd-11ea-8863-ac1428dce5e6.png">
<img width="331" alt="Screen Shot 2020-09-04 at Sep 04  4 43 14 PM" src="https://user-images.githubusercontent.com/1425051/92291518-ee2f3900-eecd-11ea-91af-390655af984d.png">
<img width="325" alt="Screen Shot 2020-09-04 at Sep 04  4 43 33 PM" src="https://user-images.githubusercontent.com/1425051/92291519-eec7cf80-eecd-11ea-8555-80ec2deda4e0.png">

**Comment by hfutrell** [comment]
@mbutterick what I believe is going on her is that in the the second image the tangent lines / derivatives match, but I think what you want is to scale those tangent lines so that the *curvatures* match. 

The curvature is given by the first and second derivatives

`k = | x' y'' - y' x'' | / (x'^2 + y'^2)^(3/2)`

https://en.wikipedia.org/wiki/Curvature#Curvature_from_arc_and_chord_length

BezierKit doesn't have explicit support for this, and only has support for getting the first derivative. The second derivative for a cubic curve is linear, which can be obtained by taking the difference between the control points twice. Something like this

```
let d0 = curve.p1 - curve.p0
let d1 = curve.p2 - curve.p1
let d2 = curve.p3 - curve.p2
let dd0 = d1 - d0
let dd1 = d2 - d1
let secondDerivative = LineSegment(p0: 1.0 / 6.0 * dd0, p1: 1.0 / 6.0 * dd1)
```

**Comment by mbutterick** [comment]
`length` is a good idea. Thanks.
