### ISSUE TITLE
feature request: permit separate x and y inputs for scale, outline, reduce 

### ISSUE THREAD

**Issue by mbutterick** [hfutrell/BezierKit#79]
Currently — am I wrong? — these operations only seem to accept a single `distance` argument that represents a distance in both x and y. It would be useful to be able to pass separate distances in x and y for these operations.

**Comment by hfutrell** [comment]
out of curiosity, do you have a use case in mind? Is it to produce outlines that have different thickness when moving in the horizontal direction versus vertical direction?

**Comment by mbutterick** [comment]
Yes. I use non-uniform offsets frequently when designing fonts to make automated weight corrections (for instance, when shrinking the standard numerals so they can be used in fractions). Scaling the glyph will give you the right exterior dimensions. But the interior “color” still has to be adjusted (usually, you need to increase the weight, because scaling down makes the glyph comparatively too light). Hence the offset operation. But because a serif design is thinner in the horizontals, I need to make a smaller adjustment in the y direction than x. 

The same logic, however, applies to any operation that moves points in the plane. (Of course, the single `d` argument would be a special case of a function that takes `dx` and `dy`)

Compare Bezier.js, which calls this operation a “[graduated offset](https://pomax.github.io/bezierjs/)”. (BTW is this project related to that one? Both sets of curve demos are displayed the same way, which seems like it can’t be coincidence)

**Comment by hfutrell** [comment]
BezierKit started as a straight port of Bezier.js to Swift but its goals have changed since then (more oriented towards paths and compatibility with CoreGraphics, doing advanced vector boolean operations such as subtract and union, etc).

as I understand it Bezier.js graduated offsets refer to offsetting in the normal and anti-normal directions, which are relative to the direction of the curve. But you're talking about offsetting relative to the x and y axis, correct? So not quite the same thing?

**Comment by mbutterick** [comment]
Sorry, yes — my analogy was imprecise. The graduated offset is indeed a different concept. I just meant it as a demonstration of the visual effect of a non-uniform offset.

<img width="144" alt="Screen Shot 2020-12-17 at Dec 17  1 35 44 PM" src="https://user-images.githubusercontent.com/1425051/102546637-cc1c8980-406c-11eb-9267-8903dcc86bc1.png">

**Comment by hfutrell** [comment]
I do have an idea for you. I have no idea if this will work, but you could try it out ...

Instead of applying different distances to x and y as arguments to the offset method (I'll call them `xDistance` and `yDistance`) you could first scale the path non-uniformly, then apply the offset, then apply the inverse scale. Something like:

```
let scaleTransform = CGAffineTransform(scaleX: yDistance / xDistance, y: 1)
let scaledPath = path.applying(scaleTransform)
let offsettedPath = path.offset(xDistance)
let finalResult = offsettedPath.applying(scaleTransform.inverted())
```

So for example in this case if `xDistance` is 2x that of `yDistance` the ratio `yDistance / xDistance` is 1/2. This means we first scale the path so that it's squeezed in the x direction. Then we apply the offset (equal in both direction). Then when we apply the inverse scale, the offset in the x direction should double.

**Comment by mbutterick** [comment]
That might work. I’ll try it. The fact that `offset` introduces new intermediate points on the curves makes me wonder if they’ll get kinked when scaling down (type design happens on an integer-valued grid, not float, so precision sometimes becomes an issue). Is there a way to reduce the incidence of those intermediate points, or are they intrinsic to the math of `offset`?

**Comment by hfutrell** [comment]
The new intermediate points occur because unfortunately because it's only possible to *approximate* the offset of a bezier curve with another bezier curve. The curvier the curve the more intermediate points must be added to ensure the approximation is reasonably good.
